"""0001_initial_schema

Revision ID: 83dc9d8ee90a
Revises: 
Create Date: 2026-09-13 15:43:06.586999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '83dc9d8ee90a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.bulk_insert(
        sa.table(
            'countries',
            sa.column('code', sa.String(length=2)),
            sa.column('name', sa.String(length=100)),
        ),
        [
            {'code': 'AT', 'name': 'Austria'},
            {'code': 'DE', 'name': 'Germany'},
        ],
    )
    op.create_table('searches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('query', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['country_code'], ['countries.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.ForeignKeyConstraint(['country_code'], ['countries.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id')
    )
    op.create_table('crawl_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('search_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('queued', 'completed')", name='ck_crawl_runs_status'),
    sa.ForeignKeyConstraint(['search_id'], ['searches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('search_id', 'idempotency_key', name='uq_crawl_runs_search_idempotency')
    )
    op.create_table('job_posts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('company', sa.String(length=300), nullable=False),
    sa.Column('canonical_url', sa.String(length=2000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_job_posts_created_at_id', 'job_posts', ['created_at', 'id'], unique=False)
    op.create_table('crawl_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('crawl_run_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('queued', 'completed')", name='ck_crawl_jobs_status'),
    sa.ForeignKeyConstraint(['crawl_run_id'], ['crawl_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artifacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('crawl_job_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('storage_key', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['crawl_job_id'], ['crawl_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artifacts')
    op.drop_table('crawl_jobs')
    op.drop_index('ix_job_posts_created_at_id', table_name='job_posts')
    op.drop_table('job_posts')
    op.drop_table('crawl_runs')
    op.drop_table('sources')
    op.drop_table('searches')
    op.drop_table('countries')
    # ### end Alembic commands ###
